export interface Language {
  code: string;
  name: string;
}

export const SupportedLanguagesAli: Language[] = [
  { code: 'ab', name: 'Abkhazian' },
  { code: 'sq', name: 'Albanian' },
  { code: 'ak', name: 'Akan' },
  { code: 'ar', name: 'Arabic' },
  { code: 'an', name: 'Aragonese' },
  { code: 'am', name: 'Amharic' },
  { code: 'as', name: 'Assamese' },
  { code: 'az', name: 'Azerbaijani' },
  { code: 'ast', name: 'Asturian' },
  { code: 'nch', name: 'Central Huasteca Nahuatl' },
  { code: 'ee', name: 'Ewe' },
  { code: 'ay', name: 'Aymara' },
  { code: 'ga', name: 'Irish' },
  { code: 'et', name: 'Estonian' },
  { code: 'oj', name: 'Ojibwa' },
  { code: 'oc', name: 'Occitan' },
  { code: 'or', name: 'Oriya' },
  { code: 'om', name: 'Oromo' },
  { code: 'os', name: 'Ossetian' },
  { code: 'tpi', name: 'Tok Pisin' },
  { code: 'ba', name: 'Bashkir' },
  { code: 'eu', name: 'Basque' },
  { code: 'be', name: 'Belarusian' },
  { code: 'ber', name: 'Berber languages' },
  { code: 'bm', name: 'Bambara' },
  { code: 'pag', name: 'Pangasinan' },
  { code: 'bg', name: 'Bulgarian' },
  { code: 'se', name: 'Northern Sami' },
  { code: 'bem', name: 'Bemba (Zambia)' },
  { code: 'byn', name: 'Blin' },
  { code: 'bi', name: 'Bislama' },
  { code: 'bal', name: 'Baluchi' },
  { code: 'is', name: 'Icelandic' },
  { code: 'pl', name: 'Polish' },
  { code: 'bs', name: 'Bosnian' },
  { code: 'fa', name: 'Persian' },
  { code: 'bho', name: 'Bhojpuri' },
  { code: 'br', name: 'Breton' },
  { code: 'ch', name: 'Chamorro' },
  { code: 'cbk', name: 'Chavacano' },
  { code: 'cv', name: 'Chuvash' },
  { code: 'ts', name: 'Tsonga' },
  { code: 'tt', name: 'Tatar' },
  { code: 'da', name: 'Danish' },
  { code: 'shn', name: 'Shan' },
  { code: 'tet', name: 'Tetum' },
  { code: 'de', name: 'German' },
  { code: 'nds', name: 'Low German' },
  { code: 'sco', name: 'Scots' },
  { code: 'dv', name: 'Dhivehi' },
  { code: 'kdx', name: 'Kam' },
  { code: 'dtp', name: 'Kadazan Dusun' },
  { code: 'ru', name: 'Russian' },
  { code: 'fo', name: 'Faroese' },
  { code: 'fr', name: 'French' },
  { code: 'sa', name: 'Sanskrit' },
  { code: 'fil', name: 'Filipino' },
  { code: 'fj', name: 'Fijian' },
  { code: 'fi', name: 'Finnish' },
  { code: 'fur', name: 'Friulian' },
  { code: 'fvr', name: 'Fur' },
  { code: 'kg', name: 'Kongo' },
  { code: 'km', name: 'Khmer' },
  { code: 'ngu', name: 'Guerrero Nahuatl' },
  { code: 'kl', name: 'Kalaallisut' },
  { code: 'ka', name: 'Georgian' },
  { code: 'gos', name: 'Gronings' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'gn', name: 'Guarani' },
  { code: 'kk', name: 'Kazakh' },
  { code: 'ht', name: 'Haitian' },
  { code: 'ko', name: 'Korean' },
  { code: 'ha', name: 'Hausa' },
  { code: 'nl', name: 'Dutch' },
  { code: 'cnr', name: 'Montenegrin' },
  { code: 'hup', name: 'Hupa' },
  { code: 'gil', name: 'Gilbertese' },
  { code: 'rn', name: 'Rundi' },
  { code: 'quc', name: "K'iche'" },
  { code: 'ky', name: 'Kirghiz' },
  { code: 'gl', name: 'Galician' },
  { code: 'ca', name: 'Catalan' },
  { code: 'cs', name: 'Czech' },
  { code: 'kab', name: 'Kabyle' },
  { code: 'kn', name: 'Kannada' },
  { code: 'kr', name: 'Kanuri' },
  { code: 'csb', name: 'Kashubian' },
  { code: 'kha', name: 'Khasi' },
  { code: 'kw', name: 'Cornish' },
  { code: 'xh', name: 'Xhosa' },
  { code: 'co', name: 'Corsican' },
  { code: 'mus', name: 'Creek' },
  { code: 'crh', name: 'Crimean Tatar' },
  { code: 'tlh', name: 'Klingon' },
  { code: 'hbs', name: 'Serbo-Croatian' },
  { code: 'qu', name: 'Quechua' },
  { code: 'ks', name: 'Kashmiri' },
  { code: 'ku', name: 'Kurdish' },
  { code: 'la', name: 'Latin' },
  { code: 'ltg', name: 'Latgalian' },
  { code: 'lv', name: 'Latvian' },
  { code: 'lo', name: 'Lao' },
  { code: 'lt', name: 'Lithuanian' },
  { code: 'li', name: 'Limburgish' },
  { code: 'ln', name: 'Lingala' },
  { code: 'lg', name: 'Ganda' },
  { code: 'lb', name: 'Letzeburgesch' },
  { code: 'rue', name: 'Rusyn' },
  { code: 'rw', name: 'Kinyarwanda' },
  { code: 'ro', name: 'Romanian' },
  { code: 'rm', name: 'Romansh' },
  { code: 'rom', name: 'Romany' },
  { code: 'jbo', name: 'Lojban' },
  { code: 'mg', name: 'Malagasy' },
  { code: 'gv', name: 'Manx' },
  { code: 'mt', name: 'Maltese' },
  { code: 'mr', name: 'Marathi' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'ms', name: 'Malay' },
  { code: 'chm', name: 'Mari (Russia)' },
  { code: 'mk', name: 'Macedonian' },
  { code: 'mh', name: 'Marshallese' },
  { code: 'kek', name: 'Kekchí' },
  { code: 'mai', name: 'Maithili' },
  { code: 'mfe', name: 'Morisyen' },
  { code: 'mi', name: 'Maori' },
  { code: 'mn', name: 'Mongolian' },
  { code: 'bn', name: 'Bengali' },
  { code: 'my', name: 'Burmese' },
  { code: 'hmn', name: 'Hmong' },
  { code: 'umb', name: 'Umbundu' },
  { code: 'nv', name: 'Navajo' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'ne', name: 'Nepali' },
  { code: 'niu', name: 'Niuean' },
  { code: 'no', name: 'Norwegian' },
  { code: 'pmn', name: 'Pam' },
  { code: 'pap', name: 'Papiamento' },
  { code: 'pa', name: 'Panjabi' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ps', name: 'Pushto' },
  { code: 'ny', name: 'Nyanja' },
  { code: 'tw', name: 'Twi' },
  { code: 'chr', name: 'Cherokee' },
  { code: 'ja', name: 'Japanese' },
  { code: 'sv', name: 'Swedish' },
  { code: 'sm', name: 'Samoan' },
  { code: 'sg', name: 'Sango' },
  { code: 'si', name: 'Sinhala' },
  { code: 'hsb', name: 'Upper Sorbian' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'sl', name: 'Slovenian' },
  { code: 'sw', name: 'Swahili' },
  { code: 'so', name: 'Somali' },
  { code: 'sk', name: 'Slovak' },
  { code: 'tl', name: 'Tagalog' },
  { code: 'tg', name: 'Tajik' },
  { code: 'ty', name: 'Tahitian' },
  { code: 'te', name: 'Telugu' },
  { code: 'ta', name: 'Tamil' },
  { code: 'th', name: 'Thai' },
  { code: 'to', name: 'Tonga (Tonga Islands)' },
  { code: 'toi', name: 'Tonga (Zambia)' },
  { code: 'ti', name: 'Tigrinya' },
  { code: 'tvl', name: 'Tuvalu' },
  { code: 'tyv', name: 'Tuvinian' },
  { code: 'tr', name: 'Turkish' },
  { code: 'tk', name: 'Turkmen' },
  { code: 'wa', name: 'Walloon' },
  { code: 'war', name: 'Waray (Philippines)' },
  { code: 'cy', name: 'Welsh' },
  { code: 've', name: 'Venda' },
  { code: 'vo', name: 'Volapük' },
  { code: 'wo', name: 'Wolof' },
  { code: 'udm', name: 'Udmurt' },
  { code: 'ur', name: 'Urdu' },
  { code: 'uz', name: 'Uzbek' },
  { code: 'es', name: 'Spanish' },
  { code: 'ie', name: 'Interlingue' },
  { code: 'fy', name: 'Western Frisian' },
  { code: 'szl', name: 'Silesian' },
  { code: 'he', name: 'Hebrew' },
  { code: 'hil', name: 'Hiligaynon' },
  { code: 'haw', name: 'Hawaiian' },
  { code: 'el', name: 'Modern Greek' },
  { code: 'lfn', name: 'Lingua Franca Nova' },
  { code: 'sd', name: 'Sindhi' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'sn', name: 'Shona' },
  { code: 'ceb', name: 'Cebuano' },
  { code: 'syr', name: 'Syriac' },
  { code: 'su', name: 'Sundanese' },
  { code: 'hy', name: 'Armenian' },
  { code: 'ace', name: 'Achinese' },
  { code: 'iba', name: 'Iban' },
  { code: 'ig', name: 'Igbo' },
  { code: 'io', name: 'Ido' },
  { code: 'ilo', name: 'Iloko' },
  { code: 'iu', name: 'Inuktitut' },
  { code: 'it', name: 'Italian' },
  { code: 'yi', name: 'Yiddish' },
  { code: 'ia', name: 'Interlingua' },
  { code: 'hi', name: 'Hindi' },
  { code: 'id', name: 'Indonesia' },
  { code: 'inh', name: 'Ingush' },
  { code: 'en', name: 'English' },
  { code: 'yo', name: 'Yoruba' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'zza', name: 'Zaza' },
  { code: 'jv', name: 'Javanese' },
  { code: 'zh', name: 'Chinese' },
  { code: 'zh-tw', name: 'Traditional Chinese' },
  { code: 'yue', name: 'Cantonese' },
  { code: 'zu', name: 'Zulu' },
];

export function getLanguageByCode(code: string): { name: string; exists: boolean } {
  const language = SupportedLanguagesAli.find(lang => lang.code === code);
  return {
    name: language?.name || '',
    exists: !!language,
  };
}

export function isLanguageSupported(code: string): boolean {
  return SupportedLanguagesAli.some(lang => lang.code === code);
} 